sudo: required
services:
  - docker

before_install:
  - docker build -t addy071/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  addy071/react-test npm test -- --coverage

after_success:
  - docker build -t addy071/multi-client ./client
  - docker build -t addy071/multi-nginx ./nginx
  - docker build -t addy071/multi-server ./server
  - docker build -t addy071/multi-worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push addy071/multi-client
  - docker push addy071/multi-nginx
  - docker push addy071/multi-server
  - docker push addy071/multi-worker
